# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='qoute',
            new_name='quote',
        ),
    ]
